spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.98.3:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#Log4g打印SqL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 